### ISSUE TITLE
Implementación de factura electrónica costarricense en odoo

### ISSUE THREAD

**Issue by nehemiascr** [CRLibre/fe-hacienda-cr-odoo#1]
Buenas, ando en busca de información o código para la factura electrónica en odoo para Costa Rica, me salió este repositorio en los resultados de Google, apreciaría su ayuda, gracias.

Nehemias

**Comment by TheCloneMaster** [comment]
Hola Nehemias,
En este momento, este repositorio es WIP, y le falta aún un tiempo para que sea funcional.
Si estás buscando algo inmediato, puedes contactar con gabriel.umana@delfixcr.com, ellos te pueden asesorar.

Saludos,
-Mario

**Comment by cewongq** [comment]
Reactivamos este proyecto y tenemos una versión más avanzada, aunque no estable al 100%
