### ISSUE TITLE
Revisar la generación notas de crédito y débito

### ISSUE THREAD

**Issue by cewongq** [CRLibre/fe-hacienda-cr-odoo#10]
Revisar el proceso de creación de nota de crédito desde una factura y cuando se crea manualmente.
1- Revisar la generación del número de documento que la secuencia sea correcta de acuerdo a como lo indica tributación.
2- ver si está bien la forma en que se agrega la referencia a la factura

**Comment by jaullo** [comment]
Notas de crédito se generan correctamente. Pendiente revisión de ND

**Comment by cewongq** [comment]
En Odoo no hay NDs. Hay que inplementarlas
