### ISSUE TITLE
Cambiar la qweb template FE para que se envíe otro por correo

### ISSUE THREAD

**Issue by crodriguez82** [CRLibre/fe-hacienda-cr-odoo#107]
Impacted versions:
Odoo 11
Steps to reproduce:
Cambiar la qweb template FE para que se envíe otro por correo
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by jaullo** [comment]
Buenos días, el qweb actual envía todos los datos requeridos por hacienda. Versiones con un mejor look and feel deberán ser desarrolladas por cada persona ya que todas las necesidades son distintas
