### ISSUE TITLE
Error al ingresar descuentos

### ISSUE THREAD

**Issue by amejia-aeropost** [CRLibre/fe-hacienda-cr-odoo#110]
Impacted versions: 11

Steps to reproduce: Ingresar una factura con descuento y validar

Current behavior: Error al intentar validar

Expected behavior: Validar de forma exitosa

Video/Screenshot link (optional):
![errorodoo](https://user-images.githubusercontent.com/40579110/49828519-bb382f80-fd51-11e8-84be-001d1e8798d2.JPG)

**Comment by amejia-aeropost** [comment]
inv_line.discount_note es texto libre.

**Comment by nehemiascr** [comment]
En la [linea 768](https://github.com/CRLibre/fe-hacienda-cr-odoo/blob/11.0/cr_electronic_invoice/models/electronic_invoice.py#L768) parece que se esta intentando redondear un string, cambie la linea por
`line['naturalezaDescuento'] = inv_line.discount_note or 'Descuento Comercial'` 

https://github.com/CRLibre/fe-hacienda-cr-odoo/blob/11.0/cr_electronic_invoice/models/electronic_invoice.py#L768

**Comment by nehemiascr** [comment]
#111 Soluciona el error

**Comment by jaullo** [comment]
Listo, pull realizado
