### ISSUE TITLE
Consulta actualización

### ISSUE THREAD

**Issue by EstebanMonge** [CRLibre/fe-hacienda-cr-odoo#129]
Si tengo instalado una versión anterior del repositorio y actualizo a la actual, tengo que realizar algún paso adicional (lógicamente un respaldo), para actualizar, o ¿con solo descomprimir y reemplazar los archivos es suficiente?

**Comment by WhiteTiger08** [comment]
Respaldar la DB y la carpeta del módulo por si necesita hacer ”rollback”. 

Luego nada más reemplaza la carpeta, va a al menú de Apps, en modo Debug actualiza la lista de aplicaciones. Y por último actualiza la aplicación de FE.
