### ISSUE TITLE
Revisar la aceptación de Notas de Crédito y Débito

### ISSUE THREAD

**Issue by cewongq** [CRLibre/fe-hacienda-cr-odoo#13]
En Tributación si algún proveedor le genera a la compañía una nota de crédito/débito, se debe aceptar, rechazar o aceptar parcialmente, cómo si fuese una factura.

**Comment by jaullo** [comment]
Aceptación NC funcionando correctamente

**Comment by cewongq** [comment]
En Odoo no hay ND
