### ISSUE TITLE
Hola, los módulos funcionan en Linux ?

### ISSUE THREAD

**Issue by NSOPORTEDESARROLLO** [CRLibre/fe-hacienda-cr-odoo#130]
Buenas tardes,

Estoy tratando de integrar el modulo en mi instalación sin embargo veo que hay un par de librerías de Python que son para windows, el módulo se puede instalar en Linux ?

**Comment by jaullo** [comment]
Si sin problema

**Comment by NSOPORTEDESARROLLO** [comment]
Listo, lo logre instalar con la versión 3.6 de ubuntu, tuve este problema:

https://github.com/CRLibre/fe-hacienda-cr-odoo/issues/126

En el issue esta la solucion
