### ISSUE TITLE
Version 12

### ISSUE THREAD

**Issue by kampha** [CRLibre/fe-hacienda-cr-odoo#131]
Cuando planean tener lista la versión para Odoo 12?

**Comment by jaullo** [comment]
No se tiene planificación aún para esta versión en corto plazo

**Comment by cewongq** [comment]
Ya se subió la primera versión 12.0, por si desea probarla

**Comment by Oswamr** [comment]
Hola, la versión que acaban de subir es beta o ya está para uso en producción?

**Comment by jaullo** [comment]
Inicialmente para testing

**Comment by Oswamr** [comment]
Tienen algun manual de configuracion? 
La instalacion todo perfecto

**Comment by jaullo** [comment]
Puede ver el manual de la v11 es lo mismo
