### ISSUE TITLE
Error al clonar en 12.0

### ISSUE THREAD

**Issue by dafeza** [CRLibre/fe-hacienda-cr-odoo#157]
Impacted versions: 12.0

Steps to reproduce:
git clone https://github.com/CRLibre/fe-hacienda-cr-odoo.git

Current behavior:
$ git clone https://github.com/CRLibre/fe-hacienda-cr-odoo.git
Cloning into 'fe-hacienda-cr-odoo'...
remote: Enumerating objects: 2300, done.
remote: Total 2300 (delta 0), reused 0 (delta 0), pack-reused 2300
Receiving objects: 100% (2300/2300), 11.57 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (1280/1280), done.
Checking connectivity... done.
: Invalid argumentreate file actualizar_clientes/static/description/Icon
: Invalid argumentreate file actualizar_clientes/static/src/Icon
: Invalid argumentreate file actualizar_clientes/static/src/css/Icon
: Invalid argumentreate file actualizar_clientes/static/src/js/Icon
: Invalid argumentreate file actualizar_clientes/static/src/xml/Icon
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Expected behavior:
clone is succesful without errors

Video/Screenshot link (optional):

**Comment by jaullo** [comment]
Se aplicaron los cambios identificados y enviados en su PR
