### ISSUE TITLE
Version 12. Módulo Faltante.

### ISSUE THREAD

**Issue by leamormo** [CRLibre/fe-hacienda-cr-odoo#160]
A la hora de intentar instalar el modulo me genera este error.

Imposible instalar el módulo "cr_electronic_invoice" porqué hay una dependencia externa no resuelta: No module named xmlsig

**Comment by eddyvalverde** [comment]
Tiene que evisar que el modulo xmlsig sea instalado con la version de pip correcta, ya sea pip, pip3, pip3.5, etc, para revisar realizas un "pip list" o en "pip3 list" para ver que los modulos estan correcamente instalados, por ejemplo, si se instaló python3-pip entonces para instalar el modulo seria "pip3 install xmlsig"

**Comment by ivanporras** [comment]
de hecho el problema persiste
