### ISSUE TITLE
Adaptar el POS en Odoo 11.0 y el manejo de tiquetes electrónicos

### ISSUE THREAD

**Issue by WhiteTiger08** [CRLibre/fe-hacienda-cr-odoo#17]

**Comment by EstebanMonge** [comment]
Hola con el fin de colaborar un poco, me interesa mucho esta función.

Es necesario que en el ticket también salga el nombre de la persona, hay casos que la persona lo pide.

Para ello se puede modificar así.

El archivo: /usr/lib/python3/dist-packages/odoo/addons/point_of_sale/static/src/xml/pos.xml

Con el siguiente codigo:
`            </div>
            <div class="receipt-user">
                User: <t t-esc="widget.pos.get_cashier().name"/><br />
                <t t-if="order.get_client()">
                    Customer: <t t-esc="order.get_client().name"/><br />
                </t>
            </div>`

**Comment by EstebanMonge** [comment]
Me parece que puede quedar mejor con:
`<div class="receipt-user"> User: <t t-esc="widget.pos.get_cashier().name"/><br /> </div>
<div class="receipt-client"><t t-if="order.get_client()"> Customer: <t t-esc="order.get_client().name"/><br /> </t> </div>`

**Comment by EstebanMonge** [comment]
Según leo el POS tiene funcionalidad para trabajar offline, cuando se emite la impresión del tiquete se genera una Orden de referencia, se tiene que dar clic en confirmar o dar clic sobre el "símbolo de wifi" para que genere el número de "Simplified Invoice".

El POS crear el número de Simplified Invoice antes de Confirmar o ¿se crea luego? He tratado de buscar los valores y no los encuentro. Tal vez si me dijeran cual es podría hacer el cambio y mandar un pull request.

Otra cosa que no sería conveniente es obtener primero el Simplified Invoice, pues restaría funcionalidad al modo offline del POS.

Por lo que he leído en USA y otros países se maneja diferente el tema de tiquete electrónico, no se obliga a que sea el mismo.

**Comment by jaullo** [comment]
Hola @EstebanMonge en el POS que se tiene de ejemplo en los repos va lo del simplified invoice, sin embargo, por legislación eso no aplica acá en CR por lo que estamos trabajandolo sin esa opción, simplemente se genera el tiquete electrónico
