### ISSUE TITLE
Error de instalación. Campos no declarados en el código python.

### ISSUE THREAD

**Issue by rcastro-tyc** [CRLibre/fe-hacienda-cr-odoo#3]
## Pasos para reproducir:
* Instalación normal del módulo `cr_electronic_invoice`

## Detalles del error:
* El campo `activated` no existe en el código python de `electronic_invoice.py` https://github.com/CRLibre/fe-hacienda-cr-odoo/blob/05ba9bb9fa173f6b48fef08e3708e6dede74d84c/cr_electronic_invoice/views/electronic_invoice_views.xml#L271
#### Log del error [pastebin](https://pastebin.com/qci1QbHc)

* El campo `state` no existe en el código python de `electronic_invoice.py` https://github.com/CRLibre/fe-hacienda-cr-odoo/blob/05ba9bb9fa173f6b48fef08e3708e6dede74d84c/cr_electronic_invoice/views/electronic_invoice_views.xml#L205
#### Log del error [pastebin](https://pastebin.com/093rzB3M)

**Comment by rcastro-tyc** [comment]
@TheCloneMaster un pequeño feedback. Excelente trabajo !

**Comment by juahidma** [comment]
Aun siguen los errores en los campos que no están declarados? alguna idea de como resolverlos.

**Comment by TheCloneMaster** [comment]
Hola, es un WIP, por eso te dan errores de campos no declarados.

Voy a tratar de actualizar este fin de semana, para subir una versión
estable.

Saludos,

**Comment by juahidma** [comment]
@TheCloneMaster pura vida

**Comment by rcastro-tyc** [comment]
Muy buen trabajo ! En lo que pueda colaborar, con todo gusto !

**Comment by gVillalobosSabanaTech** [comment]
Hola pregunta, cunado intento instalar me manda el siguiente error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
    raise ValueError(message)
ValueError: Modelo no encontrado: res.country.county

Estoy usando la version 11 de odoo

adjuntos el archivo completo con el log de error
Gracias, gran aporte a la comunidad de odoo
[error.txt](https://github.com/CRLibre/fe-hacienda-cr-odoo/files/2113048/error.txt)

**Comment by rcastro-tyc** [comment]
Hola @gVillalobosSabanaTech !
El módulo, esta desarrollado para la version 10.0, por lo que creo que el error es de compatibilidad.

Si tiene un par de errores, pero es de campos no declarados en los archivos ``.py``

Saludos.

**Comment by dceevp** [comment]
Hola, como se puede solucionar lo de los campos no declarados en el .py? estoy realizando pruebas en un odoo 10.0

**Comment by cewongq** [comment]
Estamos reactivando el proyecto y tenemos una versión un poco más estable
