### ISSUE TITLE
Como se configura los modulos para que funcione

### ISSUE THREAD

**Issue by Alukarl** [CRLibre/fe-hacienda-cr-odoo#35]
Instale sus modulos, pero ahora no tenemos claro como se configuran, queremos saber cosas como que se debe poner en Usuario de Api y Password de Api, o cual es el callback url que se debe configurar, que se debe incluir en Código para Firmar Api?
Si existe un manual de configuración o algún punto de referencia para saber como se debe configurar seria muy util.
Actualmente nosotros lo configuramos así, pero no sabemos que falta.
![46487413-28ad6a00-c7bd-11e8-87b8-6bb469b2287b](https://user-images.githubusercontent.com/20672301/46492265-446b3d00-c7ca-11e8-8f62-5a7343f63c50.png)

**Comment by cewongq** [comment]
Esos son los datos para utilizar el API de CRLibre. Debe instalarlo para poder usar este módulo.
https://crlibre.org/factura-electronica/
