### ISSUE TITLE
POS Genera Doble Facturación

### ISSUE THREAD

**Issue by jaullo** [CRLibre/fe-hacienda-cr-odoo#49]
Al utilizar el POS e indicarle que se desea generar una factura y por tanto se le añade un cliente se genera un doble registro. Es decir, el módulo genera un Tiquete Electrónico y una Factura Electrónica

**Comment by TheCloneMaster** [comment]
Así funciona Odoo de fábrica, no es un problema propio de los módulos de FE...

Además, ahora un TE tiene la misma validez que una FE, por lo que no debería hacer falta generar FE si ya se tiene TE.  Nosotros bloqueamos la creación de facturas desde POS, así se evita el problema...

**Comment by jaullo** [comment]
Fixed
