### ISSUE TITLE
Error en la instalación 

### ISSUE THREAD

**Issue by juahidma** [CRLibre/fe-hacienda-cr-odoo#54]
Estoy procediendo a realizar la instalación, pero me sale el siguiente error, 
Modelo no encontrado: exoneration

Error de contexto:
Vista `exoneration.form`

**Comment by jaullo** [comment]
Favor brindar mas detalles, tal a como lo define el template de github

Servidor, versión, pasos de instalación, pasos para reproducir el error, etc

**Comment by jaullo** [comment]
No info
