### ISSUE TITLE
Descripción con caracteres especiales

### ISSUE THREAD

**Issue by EstebanMonge** [CRLibre/fe-hacienda-cr-odoo#70]
Si la descripción viene con comillas ( " ) se rechaza la factura y se genera el siguiente error:
 <DetalleMensaje>El comprobante electrónico tiene los siguientes errores: 
[codigo, mensaje, fila, columna
-1, "cvc-complex-type.2.4.b: The content of element 'DetalleServicio' is not complete. One of '{"https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica":LineaDetalle}' is expected.", 37, 44]</DetalleMensaje>

**Comment by jaullo** [comment]
Gracias por reportalo, se van a relizar algunas verificaciones

**Comment by jaullo** [comment]
A pesar de que inicialmente no se contemplan nombres con caracteres "", se aplica fix que corrige el problema en la versión 11. Se debe actualizar a la última versión
