### ISSUE TITLE
Exoneraciones

### ISSUE THREAD

**Issue by crodriguez82** [CRLibre/fe-hacienda-cr-odoo#71]
Buenas una consulta por favor

en la parte de exoneración.

Nombre = que debería ir acá?
Código = que debería ir acá?
Tipo = que debe ir acá?

Gracias por la ayuda

**Comment by jaullo** [comment]
Buenas, los datos son los que se encuentran en los anexos y estructuras. Por ejemplo, Ordenes de Compra de Instituciones Públicas, los códigos respectivos de cada uno de esos valores son los que van en la exoneración

**Comment by cewongq** [comment]
Eso es la información que debe proporcionarle el cliente cuando le solicita que le aplique la exoneración.
