### ISSUE TITLE
Error al ingresar descuentos

### ISSUE THREAD

**Issue by mejia2089** [CRLibre/fe-hacienda-cr-odoo#82]
A la hora ingresar descuentos por linea es rechazado por hacienda ya que no lleva la naturaleza descuento, que se supone es el dato que se coloca en el campo "Nota de descuento" el cual es texto libre; el siguiente archivo requiere ser modificado cr_electronic_invoice\models\electronic_invoice.py
Se debe de corregir esta linea (716)
    natu_descuento = round(inv_line.discount_note, 2) or ''
por esta
   natu_descuento = inv_line.discount_note

**Comment by cewongq** [comment]
¿De cuál versión está hablando?

**Comment by amejia-aeropost** [comment]
@cewongq hace un par de semanas lo baje e instale la version 11, debe de haber cambiado; ahora veo esto en la linea 813; line["naturalezaDescuento"] = round(inv_line.discount_note, 2) or ''; esa linea era el detonante del error; por si pueden revisarlo, yo hice la correccion localmente y me funciona.

**Comment by mejia2089** [comment]
@cewongq hace un par de semanas lo baje e instale la version 11, debe de haber cambiado; ahora veo esto en la linea 813; line["naturalezaDescuento"] = round(inv_line.discount_note, 2) or ''; esa linea era el detonante del error; por si pueden revisarlo, yo hice la correccion localmente y me funciona.

**Comment by cewongq** [comment]
¿Esto sigue siendo un error o era que tenía una versión desactualizada?

**Comment by crodriguez82** [comment]
voy a bajar la última versión para probar
