### ISSUE TITLE
Tiquete POS y Archivo PDF de Factura Odoo 11

### ISSUE THREAD

**Issue by leamormo** [CRLibre/fe-hacienda-cr-odoo#96]
A la hora de generar los comprobantes de POS y Facturación los no se cargar los datos de Token y Calve numerica existe alguna forma de incluirlos?

**Comment by jaullo** [comment]
Buenos días, si existe forma, aunque un poco complicada. Sin embargo, en este momento no estamos trabajando el POS, estamos dando prioridad al modulo de FE

**Comment by leamormo** [comment]
Gracias Jaullo,

**Comment by leamormo** [comment]
Algún participante que tenga en código xml.
